name: build docker image

on: 
  push: # Trigger workflow only on push events
    branches: # ... for these branches
      - main
      - add_dockerfile
    tags: # and if event has a tag including hierarchical tags like v1.0/beta
      - '**' 
jobs:
  build-docker:
    name: build docker container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        base-tag: ["22.08-py3", "21.12-py3"]
        target: ["main", "actions_runner"]
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
        
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/opengptx/obmd
          tags: |
            type=raw,value=${{ matrix.base-tag }}-${{ matrix.target}}-${{github.ref_name}}
            type=raw,value=${{ matrix.base-tag }}-${{ matrix.target}}-${{github.sha}}
            type=raw,value=${{ github.run_id }}
            
      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: BASE_TAG=${{ matrix.base-tag }}
          target: ${{ matrix.target}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image Metadata
        run: echo '${{ steps.build.outputs.metadata }}'