name: build docker image

on: [push]

jobs:
  build-docker:
    name: build docker container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
        
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/opengptx/obmd
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.run_id }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            
      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: BASE_TAG=22.08-py3
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image Metadata
        run: echo '${{ steps.build.outputs.metadata }}'