name: Run all tests
on:
  # enable to manually trigger the tests
  workflow_dispatch:
  pull_request:
    paths:
      - "**.py"


jobs:
  build-docker:
    name: build docker container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
        
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/opengptx/${{ matrix.path_to_dockerfile }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.run_id }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            
      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.path_to_dockerfile }}
          build-args: ${{ inputs.build_args }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image Metadata
        run: echo '${{ steps.build.outputs.metadata }}'
        
    
  test-code:
    name: Test code on gpu
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cat readme
        run: cat README.md
      
      - name: GPU check
        run: nvidia-smi
      
      - name: Environment
        run: printenv

      - name: Full check
        run: |
          export PATH=/opt/conda/lib/python3.8/site-packages/torch_tensorrt/bin:/opt/conda/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin:/opt/tensorrt/bin
          pytest tests/test_training_debug.py
